#!/bin/tcsh -f

# Need to have access to the Jython netlister program
set netlister_dir = ~/Documents/Development/git/netlister
which netlister.py > /dev/null
if ($status != 0) then
   setenv CLASSPATH ${netlister_dir}/src:$CLASSPATH
   setenv PATH      ${netlister_dir}/src:$PATH
   rehash
endif

setenv TERM xterm


cp autorouter.ctl /tmp

make cpc_ram_board.net
make cpc_ram_board.scr

make cpc_ram_board_9572xl.net
make cpc_ram_board_9572xl.scr

cp autorouter_74.ctl /tmp
make cpc_ram_board_74.scr
make cpc_ram_board_74.net
