#!/bin/tcsh -f

# Need to have access to the Jython netlister program
set netlister_dir = ../../../netlister
which netlister.py > /dev/null
if ($status != 0) then
   setenv CLASSPATH ${netlister_dir}/src:$CLASSPATH
   setenv PATH      ${netlister_dir}/src:$PATH
   rehash
endif

setenv TERM xterm



cp ../../common_pcb/autorouter.ctl /tmp
cp design_rules.dru /tmp

make cpc_sixrom.scr  -f ../../common_pcb/Makefile
make cpc_sixrom.net -f ../../common_pcb/Makefile
