#!/bin/tcsh -f

# Need to have access to the Jython netlister program
set netlister_dir = ~/Documents/Development/git/netlister
which netlister.py > /dev/null
if ($status != 0) then
   setenv CLASSPATH ${netlister_dir}/src:$CLASSPATH
   setenv PATH      ${netlister_dir}/src:$PATH
   rehash
endif

setenv TERM xterm


cp ../../common_pcb/autorouter.ctl /tmp

make cpc_ram_board.net -f ../../common_pcb/Makefile
make cpc_ram_board.scr -f ../../common_pcb/Makefile

make cpc_ram_board_9572xl.net -f ../../common_pcb/Makefile
make cpc_ram_board_9572xl.scr -f ../../common_pcb/Makefile

cp ../../common_pcb/autorouter_74.ctl /tmp

make cpc_ram_board_74.scr ARGS='"-D ALT_POWER=1"' -f ../../common_pcb/Makefile
make cpc_ram_board_74.net ARGS='"-D ALT_POWER=1"' -f ../../common_pcb/Makefile



