#!/bin/tcsh -f

# Need to have access to the Jython netlister program
set netlister_dir = ~/Documents/nas/Development/git/netlister
which netlister.py > /dev/null
if ($status != 0) then
   setenv CLASSPATH ${netlister_dir}/src:$CLASSPATH
   setenv PATH      ${netlister_dir}/src:$PATH
   rehash
endif

setenv TERM xterm

cp ../../common_pcb/autorouter_74.ctl /tmp

make cpc_backplane.scr  -f ../../common_pcb/Makefile
make cpc_backplane.net -f ../../common_pcb/Makefile
make cpc_edge_adapter.scr  -f ../../common_pcb/Makefile
make cpc_edge_adapter.net -f ../../common_pcb/Makefile
#make cpc_rc2014.scr  -f ../../common_pcb/Makefile
#make cpc_rc2014.net -f ../../common_pcb/Makefile
