#!/bin/tcsh -f

# Need to have access to the Jython netlister program
set netlister_dir = ~/Documents/Development/git/netlister
which netlister.py > /dev/null
if ($status != 0) then
   setenv CLASSPATH ${netlister_dir}/src:$CLASSPATH
   setenv PATH      ${netlister_dir}/src:$PATH
   rehash
endif

setenv TERM xterm


cp autorouter_74.ctl /tmp

make cpc_lowrom_board.scr -f ../../common_pcb/Makefile
make cpc_lowrom_board.net -f ../../common_pcb/Makefile


